language: node_js

node_js:
  - 'node'

sudo: false

branches:
  only:
  - master

install:
  - yarn

cache:
  directories:
    - node_modules

script:
  - yarn run lint
  - yarn run test

matrix:
  fast_finish: true

git:
  depth: 1