language: node_js

node_js:
  - 'node'

sudo: false

branches:
  only:
  - master

install:
  - npm install --registry=http://registry.npm.taobao.org

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test

matrix:
  fast_finish: true

git:
  depth: 1